class Player {
  constructor(
    {
      uid,
      name,
      attributes,
      skills,
    }
  ) {
    this.uid = uid;
    this.name = name;
    this.attributes = attributes;
    this.skills = skills;
  }
}

export const PlayerTeste = {
  personal: {
    name: "Kirito",
    uid: "0000000",
  },
  attributes: {
    base: {
      agility: {
        name: "agilidade",
        level: 1,
        description: "Capacidade de mudar a velocidade de partes do corpo.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,  
        exp: 0,
        expToUp: 100,
      },
      strenght: {
        name: "força",
        level: 1,
        description: "Capacidade de mover ou sustentar cargas.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      intelligence: {
        name: "inteligência",
        level: 1,
        description: "Capacidade de compreender e interferir no mundo ao redor.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      spirituality: {
        name: "espiritualidade",
        level: 1,
        description: "Capacidade de conexão com e aproveitamento do mundo que não está necessáriamente ao redor.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      resistance: {
        name: "resistência",
        level: 1,
        description: "Capacidade de persistir realizando esforços.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
    },
    battle: {
      physicalDamage: {
        name: "dano físico",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      magicDamage: {
        name: "dano mágico",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      blockChance: {
        name: "chance de bloqueio",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      blockAmount: {
        name: "quantidade bloqueada",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      magicResistance: {
        name: "resistência mágica",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      attackSpeed: {
        name: "velocidade de ataque",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      dodgeRate: {
        name: "taxa de desvio",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      criticalChance: {
        name: "chance de crítico",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      criticalDamage: {
        name: "dano crítico",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      counterAttackChance: {
        name: "chance de contra ataque",
        level: 1,
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
    },
    adventure: {
      walkSpeed: {
        medium: 0,
        maximun: 0,
        costPerSpeedPerTime: 0,
        exp: 0,
        expToUp: 100,
      },
    },
    senses: {
      vision:{
        name: "visão",
        level: 1,
        description: "Detecta a luz através dos olhos.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,  
        exp: 0,
        expToUp: 100,
      },
      hearing:{
        name: "audição",
        level: 1,
        description: "Capta ondas sonoras através do ouvido.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      smell:{
        name: "olfato",
        level: 1,
        description: "Percebe odores através de receptores no nariz que identificam moléculas químicas.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      taste:{
        name: "paladar",
        level: 1,
        description: "Reconhece sabores através das papilas gustativas na língua, que detectam cinco gostos básicos: doce, salgado, azedo, amargo e umami.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      touch:{
        name: "tato",
        level: 1,
        description: "Sensação captada por receptores na pele que percebem pressão, temperatura, dor e textura..",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      proprioception:{
        name: "propriocepção",
        level: 1,
        description: "Percepção do próprio corpo no espaço, auxiliada por sensores nos músculos, articulações e ouvido interno.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      equilibrium:{
        name: "equilíbrio",
        level: 1,
        description: "Mantido pelo sistema vestibular no ouvido interno, que detecta mudanças na posição da cabeça e ajuda na orientação.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      nociception:{
        name: "nocicepção",
        level: 1,
        description: "Sensação de dor, ativada por estímulos físicos ou químicos que indicam danos ao corpo.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      termoception:{
        name: "termocepção",
        level: 1,
        description: "Sensação de calor e frio através de receptores na pele.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      interoception:{
        name: "interocepção",
        level: 1,
        description: "Percepção de processos internos do corpo, como fome, sede, batimentos cardíacos e níveis de oxigênio.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      eletric: {
        name: "elétrico",
        level: 1,
        description: "Habilidade de detectar campos elétricos na água.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      magnetic:{
        name: "magnétigo",
        level: 1,
        description: "Capacidade de perceber o campo magnético da Terra para orientação e navegação.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      eccho:{
        name: "eco",
        level: 1,
        description: "Uso de ondas sonoras refletidas para mapear o ambiente.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      vibration:{
        name: "vibração",
        level: 1,
        description: "Capacidade de detectar vibrações.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      infrared:{
        name: "infravermelho",
        level: 1,
        description: "Percepção de calor emitido por outros organismos.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      },
      higroreception: {
        name: "higrocepção",
        level: 1,
        description: "Sensibilidade à umidade do ar.",
        current: 0,
        equipmentBonus: 0,
        skillBonus: 0,
        exp: 0,
        expToUp: 100,
      }
    }
  },
  experience: {
    level: 1,
    current: 0,
  },
  skills: {
    points: {
      current: 0,
      max: 5,
    },
    data: [
      {
        id: "00001",
        name: "soco",
        icon: {
          src: "src/assets/punch-skill-icon.jpg",
          alt: "punch",
        },
        base: {
          offensive: 4,
          defensive: 1,
          cooldown: 1000,
          experience: 100,
        },
        cost: {
          mana: 0,
          stamina: 10,
          soul: 0,
          health: 0,
        },
        details: {
          description: "Golpes desferidos com as mãos", 
          type: "target",
          nature: "physical",
        },
        experience: {
          level: 1,
          experience: 0,
          usedPoints: 0,
          proeficiency: 1,
          executions: 0,
        },
        effects: [
          {
            name: "fratura",
            level: 1,
            rate: 0.08,
          }
        ],
        tree: [
          {name: "jab", degree: 1},
          {name: "direto", degree: 1},
          {name: "cruzado", degree: 1},
          {name: "upper", degree: 1},
          {name: "2 golpes", degree: 2},
          {name: "3 golpes", degree: 3},
          {name: "4 golpes", degree: 4}
        ],
      },
      {
        id: "00023",
        name: "barreira de água",
        icon: {
          src: "src/assets/water-wall.jpeg",
          alt: "punch",
        },
        base: {
          offensive: 4,
          defensive: 1,
          cooldown: 1000,
          experience: 100,
        },
        cost: {
          mana: 150,
          stamina: 10,
          soul: 0,
          health: 0,
        },
        details: {
          description: "Golpes desferidos com as mãos", 
          type: "target",
          nature: "water",
        },
        experience: {
          level: 1,
          experience: 0,
          usedPoints: 0,
          proeficiency: 1,
          executions: 0,
        },
        effects: [
          {
            name: "fratura",
            level: 1,
            rate: 0.08,
          }
        ],
        tree: [
          {name: "jab", degree: 1},
          {name: "direto", degree: 1},
          {name: "cruzado", degree: 1},
          {name: "upper", degree: 1},
          {name: "2 golpes", degree: 2},
          {name: "3 golpes", degree: 3},
          {name: "4 golpes", degree: 4}
        ],
      },
    ]
  }
}